name: Sync to GitLab

on:
  push:
    branches:
      - master  # Ya koi aur branch jo aap sync karna chahte hain

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'yogesh-webinfomart'
        git config --global user.email 'yogesh@webinfomart.com'

    - name: Add GitLab Remote
      run: |
        git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/test9793321/django_project.git

    - name: Fetch from GitLab
      run: |
        git fetch gitlab

    - name: Push to GitLab
      run: |
        git remote -v
        git pull
        git push gitlab master
